### ISSUE TITLE
Subsequent Runs on Materialized Views Failing

### ISSUE THREAD

**Issue by amychen1776** [databricks/dbt-databricks#412] opened 2023-08-10 13:32 UTC
### Describe the bug
After the initial run of a model materialized as a materialized view, subsequent runs are failing with this error message 
```
  Error during request to server: MALFORMED_REQUEST: Client dbt-databricks/1.6.0 is not supported for SQL warehouses.SimbaJDBCDriver 2.6.14, SimbaODBCDriver 2.6.15 or above is required.
```
After running the target run sql: 
```
refresh materialized view `partner_engineering_demo_dev`.`dbt_achen`.`dim_customers`
```

 in the Databricks sql editor, I got a much better error message:
```
REFRESH statements cannot contain ' ', '\n', '\r', '\t' inside unquoted resource paths.line 1, pos 0

== SQL ==
refresh materialized view `partner_engineering_demo_dev`.`dbt_achen`.`dim_customers``
^^^
```

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

1.  I created this dbt model: 
```
{{ config(
    materialized = 'materialized_view',
    tblproperties = {
'delta.enableChangeDataFeed': 'true'}
) }}


with customer as (

    select * from {{ ref('stg_tpch_customers') }}

),
nation as (

    select * from {{ ref('stg_tpch_nations') }}
),
region as (

    select * from {{ ref('stg_tpch_regions') }}

),
final as (
    select 
        customer.customer_key,
        customer.name,
        customer.address,
        {# nation.nation_key as nation_key, #}
        nation.name as nation,
        {# region.region_key as region_key, #}
        region.name as region,
        customer.phone_number,
        customer.account_balance,
        customer.market_segment
        -- new column
    from
        customer
        inner join nation
            on customer.nation_key = nation.nation_key
        inner join region
            on nation.region_key = region.region_key
)
select 
    *
from
    final
order by
    customer_key
```
2. Run `dbt run -s dim_customers `
3. It should be successful.
4. Run `dbt run -s dim_customers ` again
5. That's where the error comes in. 

### Expected behavior
I expect Databricks to refresh the model (especially since you don't support the on_configuration_change fields. 

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
13:19:06  Running with dbt=1.6.0
13:19:06  dbt version: 1.6.0
13:19:06  python version: 3.9.17
13:19:06  python path: /usr/local/opt/python@3.9/bin/python3.9
13:19:06  os info: macOS-13.4.1-x86_64-i386-64bit
13:19:08  Using profiles dir at /Users/amychen/.dbt
13:19:08  Using profiles.yml file at /Users/amychen/.dbt/profiles.yml
13:19:08  Using dbt_project.yml file at /Users/amychen/dev/databricks_dbt_partner_demo/dbt_project.yml
13:19:08  adapter type: databricks
13:19:08  adapter version: 1.6.0
13:19:08  Configuration:
13:19:08    profiles.yml file [OK found and valid]
13:19:08    dbt_project.yml file [OK found and valid]
13:19:08  Required dependencies:
13:19:08   - git [OK found]
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by susodapop** [comment] 2023-08-22 15:48
We've got eyes on this. Updates soon.

**Comment by susodapop** [comment] 2023-08-23 20:42
I'm struggling to find a way to reproduce this. Are you using a serverless sql warehouse?

It seems that this is the real error:

>   Error during request to server: MALFORMED_REQUEST: Client dbt-databricks/1.6.0 is not supported for SQL warehouses.SimbaJDBCDriver 2.6.14, SimbaODBCDriver 2.6.15 or above is required.

Because the second error you posted is just the result of a bad copy-paste into the SQL editor.

> REFRESH statements cannot contain ' ', '\n', '\r', '\t' inside unquoted resource paths.line 1, pos 0
> 
> == SQL ==
> refresh materialized view `partner_engineering_demo_dev`.`dbt_achen`.`dim_customers``
> ^^^

**Comment by susodapop** [comment] 2023-08-23 22:33
After further research we believe the issue is most likely that you are running this model in a workspace without DBSQL serverless enabled. MV is currently in public preview while we iron out some of the kinks in the error messages. But per the [docs](https://docs.databricks.com/en/sql/user/materialized-views.html), serverless is required for Materialized Views.

I'm working on a PR to the dbt documentation that makes this clearer. And have forwarded this feedback to the relevant internal team to see about a more actionable error message.

All this, of course, assumes that you see this error in a non-serverless workspace. If it occurs in a workspace with serverless enabled then we'll need to dig deeper.

**Comment by susodapop** [comment] 2023-08-24 16:20
Closing this for now. Feel free to reopen.

**Closed by susodapop** 2023-08-24 16:20 UTC
Labels: not an issue
