### ISSUE TITLE
Expose access_control_list in the job submission for dbt python models

### ISSUE THREAD

**Issue by srggrs** [databricks/dbt-databricks#484] opened 2023-10-24 01:33 UTC
### Describe the feature
Would love to have the `access_control_list` item in the job submission of dbt python models as per Databricks API
https://docs.databricks.com/api/workspace/jobs/create

### Additional context
I need to add the can read permission so the user is able to debug the errors of a dbt python model by accessing Databricks workflow/job page

### Who will this benefit?
Everyone has better access control on the jobs submitted, ie debugging use case as described above

### Are you interested in contributing this feature?
I am keen to contribute, just need to pointed out in the right direction. CHeers

**Comment by benc-db** [comment] 2023-11-10 17:07
Thanks for the suggestion.  If you are interested in contributing this feature, I believe all of the affected code should be in python_submissions.py.  It doesn't look like we currently use that API, so I'm worried you might have an uphill climb.

Otherwise, it might be a while until we can get to this feature, though it does seem worthwhile.

**Comment by benc-db** [comment] 2023-11-10 17:11
Closing this instance as a duplicate of #474

**Closed by benc-db** 2023-11-10 17:11 UTC
Labels: duplicate, enhancement, help wanted
