### ISSUE TITLE
Send dbt model and column descriptions to Databricks as table and column comments

### ISSUE THREAD

**Issue by mreistadvipps** [databricks/dbt-databricks#264] opened 2023-01-30 10:03 UTC
### Describe the feature
Send dbt model and column descriptions to Databricks as table and column comments. Models created through dbt are naturally documented through dbt. Getting that documentation to Databricks as comments is non-trivial. Having table comments with column comments in Databricks automatically generated through dbt would enrich the Databricks Data UI for both data producers and consumers. As both dbt docs and Databricks comments support markdown, they should be compatible with each other.

In case this is not desirable for everyone, it could be implemented for example as a flag, either on dbt project level or as a dbt model config, or as an on-run-end operation.

### Who will this benefit?
I think this could be a great addition to teams using Databricks with dbt, especially those using Unity Catalog. This would be great for engineers to have documentation available in the Databricks UI, and particularily for data consumers that could find data documentation in the same place as they consume data.

**Comment by VippsMe** [comment] 2023-01-30 11:02
SmartTenkt @mreistadvipps!
Would be a nice function when the project mature and we're ready for smart integrations! 👏

**Comment by ueshin** [comment] 2023-01-30 19:21
Hi @mreistadvipps, thanks for raising the issue.

I guess this is a duplicate of #247.
Have you tried [`persist_docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs)?

**Comment by mreistadvipps** [comment] 2023-01-31 15:30
> Hi @mreistadvipps, thanks for raising the issue.
> 
> I guess this is a duplicate of #247.
> Have you tried [`persist_docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs)?

Thank you @ueshin, I didn't know about that config. That solves it for me. Closing the issue.

**Closed** 2023-01-31 15:31 UTC
Labels: enhancement
