### ISSUE TITLE
dbt-databricks error connecting from linux

### ISSUE THREAD

**Issue by durbinar** [databricks/dbt-databricks#308] opened 2023-04-10 15:48 UTC
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by durbinar** [comment] 2023-04-10 15:54
OS: Redhat Linux 8
Python version: 3.8.13
dbt-core version: 1.4.5
spark version      : 1.4.1
databricks           : 1.4.2

connecting via proxy

**Comment by susodapop** [comment] 2023-04-10 16:16
Thanks for your report. The issue is your proxy, which dbt-databricks nominally supports but currently fails because of a bug in the underlying `thrift` library that we use to communicate with Databricks clusters. Your issue is a duplicate of https://github.com/databricks/dbt-databricks/issues/111

We will merge the proxy fix into databricks-sql-connector ASAP and cut a new release of dbt-databricks that incorporates that fix.

**Closed by susodapop** 2023-04-10 16:16 UTC
Labels: bug

**Comment by durbinar** [comment] 2023-04-11 13:37
> Thanks for your report. The issue is your proxy, which dbt-databricks nominally supports but currently fails because of a bug in the underlying `thrift` library that we use to communicate with Databricks clusters. Your issue is a duplicate of #111
> 
> We will merge the proxy fix into databricks-sql-connector ASAP and cut a new release of dbt-databricks that incorporates that fix.

@susodapop thanks for your reply, have small doubts about connector security, and whether it was secure enough to pass the token, no idea why this url: fishtownanalytics-collector-1340672531.us-east-1.elb.amazonaws.com  appears when i debug the connection issue, some concerns about connection info were being logged in some other server !?
