### ISSUE TITLE
decrease in job performance for dbt docs generate 

### ISSUE THREAD

**Issue by jennlw** [databricks/dbt-databricks#608] opened 2024-03-07 01:48 UTC
### Describe the bug
When upgrading environments in dbt from v1.6 to v1.7, there were 4 times more log lines in the output of a job running the "dbt docs generate" step. At first glance, it seems v1.7.7 is scanning more metadata. Search for "describe table" term in both log files. v1.6.9 log doesn't have any matches, v1.7.7 has 3.1K matches. 

This has led to a performance difference. For example a customer reported that on 1.6.9 the job run was taking 32 seconds, after upgrading it increased to 11+ minutes. 

What dbt Support is seeing:
I looked into this with our engineers, and wanted to submit this case based on our findings. 

Our best guess is that this is happening due to a change in behavior in the dbt-databricks adapter. The noticeable difference in the logs is the huge increase in the number of "describe table <relation>..." statements being made against Databricks. We tracked this down to how dbt-databricks persists docs, in particular, how it gets the column comments from Databricks. It appears to do this one table at a time in 1.7. The _get_columns_for_catalog() function defined in the Databricks adapter seems to be getting called a lot more in 1.7. We are not sure why.

We are not sure if this could be something dbt-databricks implemented between 1.6 and 1.7, or if it could be something implemented because of a change we made. We would appreciate if someone could take a look with your better understanding of the adapter.

### Steps To Reproduce
Create a job that has "Generate docs on run" checked. 
Run the job on 1.6 and note the time the dbt docs generate step takes
Run the job on 1.7 and note the time that dbt docs generate steps takes

I tested with a very simple setup and only a handful of models. I could see each test that 1.7 ran a few seconds slower than 1.6. This is not significant when talking about a simple model setup. However, for a customer with a larger data set and a multitude of models the timing difference is considerable. 

### Expected behavior
After upgrading from 1.6 to 1.7 the expected behavior would be for dbt docs generate step to not increase significantly.

### Screenshots and log output
debug logs attached, please keep in mind this is the smaller dataset I was testing with as mentioned under steps to reproduce. The difference is very minuscule (6s vs 9s). I do have the full customer logging for debugging, but cannot attach it to here. Please feel free to reach out to me if you need more information. 

### System information
**The output of `dbt --version`:**
```
1.7.8
```
databricks version: 1.7.8

*Please note, customer was using 1.7.7 when they first saw this. 

**The operating system you're using:**
I was using macOS Sonoma when testing

### Additional context
Please feel free to reach out with any questions. Thank you!

[1.6-debug.log](https://github.com/databricks/dbt-databricks/files/14517589/1.6-debug.log)
[1.7-debug.log](https://github.com/databricks/dbt-databricks/files/14517590/1.7-debug.log)

**Comment by benc-db** [comment] 2024-03-11 17:39
So, we are calling _get_columns_for_catalog() more so that we are calling alter less...it is interesting to hear that you believe this is leading to performance degradation, as we implemented this to improve performance: previously we would call alter column for every column on every incremental run.  Now we grab the columns and compare, so that we can call alter only for changed columns.  Fundamentally, the issue is that we don't have a bulk alter statement in Databricks, something we're working on getting fixed internally; as a result, previous behavior was call an alter statement for every column on every incremental run.  Now behavior is call get columns for every table, so that if the description hasn't changed, we don't need to call alter table.  Happy to hear suggestions where we can improve.

**Comment by jennlw** [comment] 2024-03-13 09:37
Thanks, benc-db, for the explanation. I appreciate it. I have suggested the customer reach out to Databricks so that they are able to provide more context and their logs directly.

**Closed** 2024-03-19 18:18 UTC
Labels: bug

**Comment by benc-db** [comment] 2024-03-20 21:14
Reopening issue because I think there is more we can do to improve.

**Comment by benc-db** [comment] 2024-03-20 22:12
@jennlw when you run `dbt docs generate` with 1.6.x, does the resulting doc site have column comments for your HMS tables?  The `describe extended` calls are how we're getting column comments to key the doc site synced with what is actually deployed, and I don't see any other way of accomplishing this for Hive Metastore.  What we could do instead is have the doc site match what is in the project, rather than what is deployed, but we'd have to do that with some sort of flag to choose between the modes of operation, as some users may prefer to pay the cost to see the comments that exist in Databricks.  @mikealfare for viz.

**Comment by ktopcuoglu** [comment] 2024-03-21 10:28
hello @benc-db , We are the dbtCloud customer who raise this issue to dbtLabs. 

We first raised the issue immediately after v1.7 (from v1.6) upgrade on dbtCloud.
We started to observe that "dbt docs generate" step in dbtCloud job failed. There were 2 significant difference when compared with most recent v1.6 log.
1) Too many "describe extended" calls, because we are using HMS as catalog, it's expected to these calls take much longer. But we want to understand if this was a feature or bugfix released with v1.7.. 
1.a) If this is a new feature, we want to understand why Dbt attempting to scan entire course database schema for all tables even they are not referenced in our project. (We have thousands objects in source schemas)
2.b) If this is a bugfix, next step for us, consider a way to exclude source schemas that are being scanning for dbt docs (except referenced tables). (--empty-catalog?)
2) Some of the "describe extended" calls failed with `<s3 path> doesn't exist, or is not a Delta table` error. We are on HMS and source tables are External. We believe this is due to underlying s3 files removed without dropping table. It may not be ideal state for a data platform. But still, IMO, these shouldn't be "error" severity for "dbt docs generate". Especially for the source tables those are not referenced in the Dbt project.

**Comment by benc-db** [comment] 2024-03-21 15:33
@ktopcuoglu I've looked at the log, and I know the issue you're describing.  I'm just wondering if, when running with 1.6.x, you actually see comments on columns on the doc site.  If you do, then these comments must be coming from your dbt project description (which is great, I think that's the solution we're going to move to anyway); what I suspected is happening is that we just don't put those comments in the generated doc site, since the only way we can get them from Databricks when using HMS is `describe table`.

**Comment by ktopcuoglu** [comment] 2024-03-22 00:37
@benc-db  TBH, I wasn't aware of if column comments were shown for **source tables** with v1.6 or not. (In our implementation, documentation practice starts from staging models, we don't document sources in the dbt project)

for the tables that were populated via dbt models, I'm sure we had have column comments in dbt docs derived from the dbt project. (and also, I was not aware of of dbt doc generate being able to merge column comments both from both dbt+database, for dbt modeled tables)
