### ISSUE TITLE
Cannot run dbt docs generate with JSON logs

### ISSUE THREAD

**Issue by robertf-b** [databricks/dbt-databricks#115] opened 2022-06-17 09:51 UTC
### Describe the bug
When running dbt docs generate with JSON logs enabled I receive an error:  `Encountered an error while generating catalog: Object of type DatabricksRelation is not JSON serializable`.
This occurs when using dbt-databricks 1.1.0 on all of locally (Windows), Docker (Linux) and the preview Databricks dbt task type.
It does not occur in earlier versions.
It does not occur with the default log format.

### Steps To Reproduce

1.  Run `dbt --log-format json docs generate`

### Expected behavior
Doc site generates correctly, with JSON logs.

### Screenshots and log output
```json
{"code": "E044", "data": {}, "invocation_id": "4240ec3d-ef2f-4772-8540-d4d522a8c717", "level": "info", "log_version": 2, "msg": "Building catalog", "pid": 1628, "thread_name": "MainThread", "ts": "2022-05-25T14:22:49.779873Z", "type": "log_line"}
{"code": "Z046", "data": {"log_fmt": null, "msg": "Encountered an error while generating catalog: Object of type DatabricksRelation is not JSON serializable"}, "invocation_id": "4240ec3d-ef2f-4772-8540-d4d522a8c717", "level": "warn", "log_version": 2, "msg": "Encountered an error while generating catalog: Object of type DatabricksRelation is not JSON serializable", "pid": 1628, "thread_name": "MainThread", "ts": "2022-05-25T14:22:49.783320Z", "type": "log_line"}
{"code": "E041", "data": {"num_exceptions": 1}, "invocation_id": "4240ec3d-ef2f-4772-8540-d4d522a8c717", "level": "error", "log_version": 2, "msg": "dbt encountered 1 failure while writing the catalog", "pid": 1628, "thread_name": "MainThread", "ts": "2022-05-25T14:22:49.792754Z", "type": "log_line"}
```

### System information
Windows:
```
Core:
  - installed: 1.1.0
  - latest:    1.1.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.1.0 - Up to date!
  - spark:      1.1.0 - Up to date!
```

**The operating system you're using:**
Windows/Linux/Databricks

**The output of `python --version`:**
Windows:
`Python 3.9.0`

**Comment by bilalaslamseattle** [comment] 2022-06-17 09:59
@ueshin @allisonwang-db I can repro this on my laptop, too.

**Comment by ueshin** [comment] 2022-06-17 18:32
@jtcohen6 Could you help take a look at this issue?

Seems like `SparkRelation` or even `BaseRelation` are not serializable.

```py
>>> json.dumps(SparkRelation.create(schema='a', identifier='b'))
...
TypeError: Object of type SparkRelation is not JSON serializable

>>> json.dumps(BaseRelation.create(schema='a', identifier='b'))
Traceback (most recent call last):
...
TypeError: Object of type BaseRelation is not JSON serializable
```

Thanks.

**Comment by ueshin** [comment] 2022-06-17 18:48
Seems like it tries to show more logs in `1.1` than `1.0`, that is breaking the command.

**Comment by jtcohen6** [comment] 2022-06-17 19:16
I'm able to reproduce this locally with the latest `dbt-databricks` + `dbt-core`. I'm trying to figure out where in the methods called by `docs generate` a `DatabricksRelation` is being passed directly into a log message, and then formatted into JSON, without any intermediate serialization steps.

`BaseRelation` (and thereby `SparkRelation` + `DatabricksRelation`) are not directly JSON serializable, but they can be converted to dictionaries that are, via meta properties of their parent class [`dbtClassMixin`](https://github.com/dbt-labs/dbt-core/blob/d257d0b44c8118328a98caac5cb916eed4c3506c/core/dbt/dataclass_schema.py#L37):

```python
>>> import json
>>> from dbt.adapters.base import BaseRelation
>>> json.dumps(BaseRelation.create(schema='a', identifier='b').to_dict())
'{"path": {"database": null, "schema": "a", "identifier": "b"}, "type": null, "quote_character": "\\"", "include_policy": {"database": true, "schema": true, "identifier": true}, "quote_policy": {"database": true, "schema": true, "identifier": true}, "dbt_created": false}'
```

**Comment by jtcohen6** [comment] 2022-06-17 19:38
I found a simple fix for this, but I'd be curious to get @nathaniel-may's take on it before merging

**Comment by bilalaslamseattle** [comment] 2022-07-21 09:56
@jtcohen6 any update on this? I'd love to close this out in the next point release.

**Comment by jtcohen6** [comment] 2022-07-22 12:46
@nathaniel-may I'd like to prioritize https://github.com/dbt-labs/dbt-core/issues/5436 for an upcoming sprint, since that's the real resolution to this issue. It looks like it's currently queued up for estimation.

It the general-purpose resolution appears to be too complex, we can put a one-off patch for this in `dbt-spark`, to unblock the user here.

**Closed** 2022-11-11 14:08 UTC
Labels: bug
