### ISSUE TITLE
Unable to run a dbt project through a Databricks Workflows

### ISSUE THREAD

**Issue by abhishek-7781** [databricks/dbt-databricks#410] opened 2023-08-09 04:08 UTC
### Describe the bug
I'm trying to run a dbt project which reads data from ADLS and writes back to ADLS using a Databricks Workflow. When I run the same project from my local machine (using python virtual environment from Visual Studio Code), it's running perfectly fine but it's throwing an error while running it from Databricks Workflow.
The dbt project is on GitHub and hence using source as GitHub Enterprise in Databricks workflow.

### Steps To Reproduce
**Databricks Workflow Details**-
Type: dbt
Source: GitHub Enterprise
Commands:
1. dbt deps
2. dbt debug
3. dbt run --threads 16 --select tag:<model_tag>

### Screenshots and log output
**Snapshot of profiles.yml file**
![image](https://github.com/databricks/dbt-databricks/assets/141800574/a6e942bd-884b-4001-b1b2-eac9704b997a)

> I'm using a Job Cluster here and not SQL Warehouse/Endpoint
> host: adb-****************.**.azuredatabricks.net
> http_path: /sql/protocolv1/o/****************/****-******-********
> token: dapi********************************************

**Error Message**-
While running the Databricks workflow, I'm getting the below error:

> 15:59:28 Configuration:
> 15:59:28 profiles.yml file [OK found and valid]
> 15:59:28 dbt_project.yml file [OK found and valid]
> 15:59:28 Required dependencies:
> 15:59:28 - git [OK found]
> 15:59:28 Connection:
> 15:59:28 host: [REDACTED]
> 15:59:28 http_path: [REDACTED]
> 15:59:28 schema: default
> 15:59:28 Registered adapter: databricks=1.6.1
> 15:59:29 databricks-sql-connector adapter: Error during request to server: {"method": "OpenSession", "session-id": null, "query-id": null, "http-code": 403, "error-message": "", "original-exception": "", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "0.7869570255279541/900.0"}
> 15:59:29 Connection test: [ERROR]

Detailed Error after running with verbose logs:

> 07:24:58 Acquiring new databricks connection 'master'
> 07:24:58 Acquiring new databricks connection 'list_schemas'
> 07:24:58 Acquiring new databricks connection 'list_schemas'
> 07:24:58 Acquiring new databricks connection 'list_schemas'
> 07:24:58 Using databricks connection "list_schemas"
> 07:24:58 Using databricks connection "list_schemas"
> 07:24:58 Using databricks connection "list_schemas"
> 07:24:58 Acquiring new databricks connection 'list_schemas'
> 07:24:58 On list_schemas: /* {"app": "dbt", "dbt_version": "1.6.0", "dbt_databricks_version": "1.6.1", "databricks_sql_connector_version": "2.7.0", "profile_name": "analytics_engineering_pipeline_synapse_app_sp", "target_name": "databricks_job", "connection_name": "list_schemas"} */
> 
> show databases
> 07:24:58 Opening a new connection, currently in state init
> 07:24:58 Using databricks connection "list_schemas"
> 07:24:58 On list_schemas: /* {"app": "dbt", "dbt_version": "1.6.0", "dbt_databricks_version": "1.6.1", "databricks_sql_connector_version": "2.7.0", "profile_name": "analytics_engineering_pipeline_synapse_app_sp", "target_name": "databricks_job", "connection_name": "list_schemas"} */
> 
> show databases
> 07:24:58 Opening a new connection, currently in state init
> 07:24:59 databricks-sql-connector adapter: Error during request to server: {"method": "OpenSession", "session-id": null, "query-id": null, "http-code": 403, "error-message": "", "original-exception": "", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "1.3058898448944092/900.0"}
> 07:25:00 Databricks adapter: <class 'databricks.sql.exc.RequestError'>: Error during request to server
> 07:25:00 databricks-sql-connector adapter: Error during request to server: {"method": "OpenSession", "session-id": null, "query-id": null, "http-code": 403, "error-message": "", "original-exception": "", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "2.635369300842285/900.0"}
> 
> 07:25:00 Databricks adapter: Database Error
> Error during request to server
> 07:25:00 Databricks adapter: Error while running:
> macro list_schemas
> 07:25:00 Databricks adapter: session-id: None
> 07:25:00 Databricks adapter: Database Error
> Error during request to server
> 07:25:00 Databricks adapter: Error while running:
> macro list_schemas
> 07:25:00 Databricks adapter: Runtime Error
> Database Error
> Error during request to server
> 07:25:00 Databricks adapter: Error while running:
> /* {"app": "dbt", "dbt_version": "1.6.0", "dbt_databricks_version": "1.6.1", "databricks_sql_connector_version": "2.7.0", "profile_name": "analytics_engineering_pipeline_synapse_app_sp", "target_name": "databricks_job", "connection_name": "list_schemas"} */
> 
> show databases
> 

### System information
**Versions**-
dbt version: 1.6.0
python version: 3.9.5
databricks adapter version: 1.6.1

**Comment by benc-db** [comment] 2023-08-16 20:09
@susodapop is the addressed by your recent work?

**Comment by followingell** [comment] 2023-08-21 17:18
I _believe_ that this is still an issue given this discussion in the [dbt Slack #db-databricks-and-spark room](https://getdbt.slack.com/archives/CNGCW8HKL/p1691753579288309).

As a workaround it seems that users (including me) are having to pin the `databricks_sql_connector` version to a version that differs from [`dbt-databricks`](https://github.com/databricks/dbt-databricks/blob/main/requirements.txt#L1) in their Databricks Workflow dbt Tasks.

**Comment by abhishek-7781** [comment] 2023-08-22 12:56
@followingell Thanks for your comment.
That's absolutely true! The following combination of versions worked for me:
**on Local Python Environment (Python 3.10.9)**
- dbt-core==1.6.0, dbt-databricks==1.6.1, databricks-sql-connector==2.7.0
- dbt-core==1.3.4/5, dbt-databricks==1.3.2, databricks-sql-connector==2.7.0

**On Databricks (Python 3.9.5)**
- dbt-core==1.3.4/5, dbt-databricks==1.3.2, databricks-sql-connector==2.1.0

**Comment by susodapop** [comment] 2023-08-24 17:12
I'm going to keep this open until we can nail down the configuration setting default that needs changed. It's a bad out-of-the-box experience to manually pin these things in worfklows.

**Comment by abhishek-7781** [comment] 2023-09-01 13:36
For some strange reason, the following version combination isn't working on Local Python Environment (Python 3.10.9) anymore.
`dbt-core==1.6.0, dbt-databricks==1.6.1, databricks-sql-connector==2.7.0`

**Comment by abhishek-7781** [comment] 2023-09-04 07:48
> No error is coming though but nothing happens either. ![image](https://user-images.githubusercontent.com/141800574/265038007-068256ac-3838-4818-8830-ad00e8a68965.png)

I got this one. It happens only when the **log-path** in **dbt_project.yml** is a relative path with a variable or environment variable mentioned in it.
For instance, the following works:
1. **log-path:** "logs"
2. **log-path:**  C:\Users\user_name\dbtprojects\logs\
But, with this one dbt is behaving as mentioned above:
3. **log-path:**  C:\Users\user_name\dbtprojects\logs\{{ var("variable", "none") }}

**Comment by abhishek-7781** [comment] 2023-09-05 09:59
> I _believe_ that this is still an issue given this discussion in the [dbt Slack #db-databricks-and-spark room](https://getdbt.slack.com/archives/CNGCW8HKL/p1691753579288309).
> 
> As a workaround it seems that users (including me) are having to pin the `databricks_sql_connector` version to a version that differs from [`dbt-databricks`](https://github.com/databricks/dbt-databricks/blob/main/requirements.txt#L1) in their Databricks Workflow dbt Tasks to avoid issues.

@followingell do you think there's any workaround to run `dbt-databricks==1.6.1` from Databricks, even pinning  `databricks_sql_connector` to a specific version? I'm really stuck trying to make this work.
![1](https://github.com/databricks/dbt-databricks/assets/141800574/91a50606-fb29-4046-b3d4-9b9dade35b83)

**Comment by followingell** [comment] 2023-09-05 10:47
@abhishek-7781 I haven't upgraded to `dbt-databricks==1.6.1` given that this issue is still open... so I can't comment on how to get this work.

I understand that there are likely many differing priorities on Databricks' side and other things I am not taking into account, however,  personally IMO this should be addressed soon by Databricks because:
1. The issue impacts a core functionality of their platform.
2. The issue is _(seemingly)_ caused by interactions between two packages that Databricks maintains.

**Comment by abhishek-7781** [comment] 2023-09-05 10:58
@followingell Yes, I know what's causing this issue - the handshake between `dbt-databricks` and `databricks-sql-connector` - specifically the access_token which the latter expects to establish the connection.
I would agree with you that this must be a high priority issue for Databricks.

Unfortunately, I had to upgrade to `dbt-databricks==1.6.1` for the ServicePrincipal/OAuth authentication which doesn't work in `dbt-databricks==1.3.2`. But anyway, we have to upgrade anytime soon no matter what, just hoping this gets resolved first.

Thanks for your response.

**Comment by benc-db** [comment] 2023-09-05 16:18
I'm investigating this and #433 now.

**Comment by benc-db** [comment] 2023-09-05 21:01
Sorry this took so long for me to truly understand the problem, but I think fundamentally your problem is using Jobs Clusters.  According to the Jobs team, only SQL Warehouses and All Purpose Clusters are supported for the dbt task on Databricks Workflows.

**Comment by abhishek-7781** [comment] 2023-09-06 04:55
@benc-db So, I'm using a Job Cluster to run the Databricks workflow, which is the usual approach to follow instead of using an All-Purpose Cluster if there are a number of workflows to run, which connects to an All-Purpose Cluster or SQL Warehouse using the PAT or OAuth to read and write the data from/to ADLS.
This is similar to my Local Python Env (instead Job Cluster) connecting with an All-Purpose Cluster or SQL Warehouse using the PAT or OAuth, which has been working fine. So I'm sure that it's not the Job Cluster that's creating this issue.

But anyway, please allow me to run a few more tests before I confirm this but for now it seems to work and resolve the stated issue. Snapshot attached for reference:
![image](https://github.com/databricks/dbt-databricks/assets/141800574/b86f248a-2014-4496-95d5-2eb1a8c545b4)

**Comment by followingell** [comment] 2023-09-06 08:13
> Sorry this took so long for me to truly understand the problem, but I think fundamentally your problem is using Jobs Clusters. According to the Jobs team, only SQL Warehouses and All Purpose Clusters are supported for the dbt task on Databricks Workflows.

Hey @benc-db,

Job Clusters definitely support dbt Tasks as part of Databricks Workflows, in fact [official documentation actually states this](https://learn.microsoft.com/en-us/azure/databricks/workflows/jobs/how-to/use-dbt-in-workflows#development-and-production-workflow):

> To run your dbt transformations in production, Databricks recommends using the dbt task in a Databricks job. By default, the dbt task will run the dbt Python process on a single node job cluster, and the dbt generated SQL against the selected SQL warehouse.

And the Databricks platform recommends this when creating dbt Workflows (see pic):
![image](https://github.com/databricks/dbt-databricks/assets/5324956/a63d0f77-832f-4276-8211-607b0da52e1a)


To your point, the **dbt generated SQL** has to be executed against a SQL warehouse (or All Purpose Cluster), however the the Python dbt process that is executed in what Databricks refers to as the 'dbt CLI cluster', which can be a Job Cluster.

**Comment by benc-db** [comment] 2023-09-06 15:38
Yes, the invocation of dbt can run on a job cluster, but the actual compute for the materializations cannot:

![image](https://github.com/databricks/dbt-databricks/assets/98852248/587fbf0c-f3f5-4693-a89f-3aadfa223e74)

https://docs.databricks.com/en/workflows/jobs/how-to/use-dbt-in-workflows.html#advanced-run-dbt-with-a-custom-profile

**Comment by benc-db** [comment] 2023-09-06 15:41
> @benc-db So, I'm using a Job Cluster to run the Databricks workflow, which is the usual approach to follow instead of using an All-Purpose Cluster if there are a number of workflows to run, which connects to an All-Purpose Cluster or SQL Warehouse using the PAT or OAuth to read and write the data from/to ADLS.

So to verify, you've only been using a jobs node for executing the dbt commands, but not as the compute target?

**Comment by benc-db** [comment] 2023-09-06 16:58
Closing as customer has resolved their issue.

**Closed by benc-db** 2023-09-06 16:58 UTC
Labels: bug

**Comment by abhishek-7781** [comment] 2023-09-07 06:41
> > @benc-db So, I'm using a Job Cluster to run the Databricks workflow, which is the usual approach to follow instead of using an All-Purpose Cluster if there are a number of workflows to run, which connects to an All-Purpose Cluster or SQL Warehouse using the PAT or OAuth to read and write the data from/to ADLS.
> 
> So to verify, you've only been using a jobs node for executing the dbt commands, but not as the compute target?

Yes, I'm using the Job Cluster for dbt instantiation to do the following:
1. setting up a Python environment
2. downloading the GIT repo contents
3. running the dbt commands
and the All Purpose Cluster for compute to do the following:
1.  reading data from the source
2. writing data to the target
