### ISSUE TITLE
on sql-warehouse incremental models always replace all the data

### ISSUE THREAD

**Issue by AntonPeniaziev** [databricks/dbt-databricks#219] opened 2022-10-18 15:15 UTC
### Describe the bug

Im running a simple model:
```
{{ config(
  materialized = 'incremental',
    incremental_strategy='merge',
  file_format = 'delta',
    unique_key='h3_10',
) }}

select "h3rferfre5" as h3_10
```

I found that when using sql-warehouse:
```
sql-serverless:
  outputs:
    dev:
      host: **
      http_path: **
      schema: hive_metastore.tube_silver_prod
      threads: 1
      token: **
      type: databricks
  target: dev
```

The model is always executes:
```
create
or replace table hive_metastore.tube_silver_prod.my_fi...
```

as a result all the data is deleted and replaced.

When running the same model with a profile that uses an interactive cluster
```
cluster:
  outputs:
    dev:
      host: ***
      http_path: ***
      schema: tube_silver_prod
      threads: 1
      token: ***
      type: databricks
  target: dev
```

the result query is as expected:
`merge into tube_silver_prod.my_first_dbt_model as DBT_INTERNAL_DEST...`

the result is merged/appended as expected

Plugins:
  - databricks: 1.2.1 - Update available!
  - spark:      1.2.0 - Update available!
Python 3.8.13

Thanks

**Comment by ueshin** [comment] 2022-10-20 22:24
I think the config `schema: hive_metastore.tube_silver_prod` is something wrong.
Could you try with `schema: tube_silver_prod`?

**Comment by bilalaslamseattle** [comment] 2022-10-22 08:16
@AntonPeniaziev I'm going to close this unless you object. Sounds like you found the root cause.

**Closed by bilalaslamseattle** 2022-10-22 08:16 UTC
Labels: bug

**Comment by AntonPeniaziev** [comment] 2022-10-23 06:04
thx for the response,
the thing is Im on AWS Glue and in order to use it I need to specify hive_metastore.tube_silver_prod, otherwise dbt will run against main metastore of databricks and that's not what I want.
if there would be an option to inject 
use catalog hive_metastore before dbt runs that would allow me to specify tube_silver_prod only.

dbt manages to read and write models to glue - the only corner case is that it ignores the merge -  probably there's some "describe" command that is executed against wrong database.

Can you help me to understand which command misleads dbt?

**Comment by AntonPeniaziev** [comment] 2022-10-23 06:05
@bilalaslamseattle @ueshin  if its possible pls reopen the issue

**Comment by ueshin** [comment] 2022-10-23 06:10
Could you try ```
catalog: hive_megastore
```?

**Comment by AntonPeniaziev** [comment] 2022-10-24 08:34
works perfectly, thanks! @ueshin 
 I didnt know that keyword
